config/routes.rb
Rails.application.routes.draw do

  devise_for :views
  devise_for :users

  root 'pages#index'

  resources :students
  resources :companies
  resources :sponsors
  resources :tasks

  post '/sponsors/upload' => 'sponsors#upload'

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?


   protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
   	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
   end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController

  def index
      @sponsors = Sponsor.all 
  end
  
  def show

      @sponsor = Sponsor.find_by_id(params[:id])
      if !current_user
        redirect_to user_session_path
      end   
  end

  def new
  end 
  
  def each

  end 

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def upload
      image = params[:image]
      File.open(image.original_filename,'wb') do |f|
          f.write image.tempfile.read
      end
      redirect_to root_path
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end 

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
	  	@task = Task.new
	end
	def create
		@task = Task.new(params[:id])
		@task.save
		
	end
	def index
		@tasks = Task.all
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def notice_message
    alert_types = { :notice => :success, :alert => :danger }

    close_button_options = { :class => "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, :class => alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag "logo.png", size:"180x60"  %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li> <%= link_to("註冊", new_user_registration_path) %> </li>
        <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!, <%= current_user.name %>  
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
          <li><%= link_to("帳號設定", edit_user_registration_path )%></li>
            <li> <%= link_to("登出", destroy_user_session_path, 
                               :method => :delete ) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iSponsor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <%= yield :css %>
</head>
<body>
 <%= render 'layouts/header' %>
 <%= notice_message  %>
 <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :js %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/aboutisponsor.html.erb
<!DOCTYPE html>
<html>

  <head>
    
    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
    
    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
    <link rel="stylesheet" href="main.css">
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
  </head>
  <body>
    <div class="nav">
      <div class="container">
      
        <ul class="pull-left">
          <li><a href="file:///Users/JazzSun/Desktop/student_company%20platform/index.html">首頁</a></li>
          
        </ul>
      
      </div>
    </div>
      <div class="jumbotron">
      <div class="container">
        <h1>iSponsor.</h1>
        <p>The startup from NCKU </p>
        <a href="#">Learn More</a>

      </div>
    </div> 

app/views/pages/homepage.html.erb
<!DOCTYPE html>
<html>

  <head>
    
    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
    
    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
    <link rel="stylesheet" href="main.css">
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
  </head>

  <body>
    <div class="nav">
      <div class="container">
      
        <ul class="pull-left">
          <li><a href="file:///Users/JazzSun/Desktop/student_company%20platform/aboutisponsor.html">關於iSponsor</a></li>
          
        </ul>
        <ul class="pull-right">
          <li><a href="#">註冊</a></li>
          <li><a href="#">登入</a></li>

        </ul>
      </div>
    </div>
   

    <div class="jumbotron">
      <div class="container">
        <h1>Provide the sponsor information you need.</h1>
        <p>Sponsor from company &Shop in over 100 companies and 200 shops.</p>
        <a href="#">Learn More</a>

      </div>
    </div> 
    
    <div class="neighborhood-guides">
     <div class="container">
     <h2> "Sponsor Company" </h2>
     <p>"We provide you the Top company those interested in student market"  </p>
     <div class="row">
     <div class="col-md-4">
     <div class="thumbnail">
        <img src="http://www.theinquirer.net/IMG/668/254668/htc-logo-1.jpg">
     </div>
     
      <div class="thumbnail">
        <img src="http://netdna.webdesignerdepot.com/uploads/2013/02/featured35@wdd2x.jpg">
     </div>
     </div>
     <div class="col-md-4">
     <div class="thumbnail">
      <img src="http://www.timglobe.com.tw/upload/file/201410091457167626038565.png" >
    </div>
    <div class="thumbnail">
      <img src="http://www2.jtf.org.tw/psyche/sportrelief/images/logo11.jpg">
    </div>
     
      </div>
     <div class="col-md-4">
     <div class="thumbnail">
      <img src="https://www-techinasia.netdna-ssl.com/wp-content/uploads/2013/02/Line-Band-app-03.png" >
    </div>
     
      </div>
     
     
    
     </div>
     </div>
     </div>

    <div class="learn-more">
    <div class="container">
    <div class="row">
    <div class="col-md-4">
    <div>
        <div>
      <h3>使用者分享 1</h3>
      <p>iSponsor真的讓我們社團拉贊助變更方便了-前AIESEC成大分會社長</p>
      <p><a href="#">See how to sponsor you</a></p>
        </div>
      <div>
      <h3>使用者分享 2</h3>
      <p>介面簡單而且能避免拉到重複的店家-電機系系會公關長</p>
      <p><a href="#">Learn more about how to sponsor</a></p>
      </div>
   
      </div>
    </div>
  </div>
  </div>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<% content_for :css do %>
<%= stylesheet_link_tag "component" %>
<%= stylesheet_link_tag "pages" %>
<%end%>
    <div class="jumbotron">
      <div class="container">
        <h1>達成企業任務  我們給你贊助</h1>
        <p>Sponsor from company&Shop in over 100 companies and 200 shops.</p>
        <a href="sponsors" color="red">贊助列表</a>

      </div>
    </div>

    <div class="neighborhood-guides">
      <div class="container">
        <h2> "贊助公司" </h2>
        <p>"We provide you the Top company those interested in student market"  </p>

          <div class="row">

            <div class="col-md-4">
              <div class="thumbnail">
                <%= image_tag("htc.jpg") %>
              </div>
              <div class="thumbnail">
                <%= image_tag("yahoo.jpg") %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="thumbnail">
                <%= image_tag("kdan.png") %>
              </div>
              <div class="thumbnail">
                <%= image_tag("uni.jpg") %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="thumbnail">
                <%= image_tag("band.png") %>
              </div>
            </div>

          </div>
        </div>
      </div>

    <div class="learn-more">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h3 >使用者分享 1</h3>
            <p>iSponsor真的讓我們社團拉贊助變更方便了-前AIESEC成大分會社長</p>
            <p><a href="#">See how to sponsor you</a></p>
            <h3>使用者分享 2</h3>
            <p>介面簡單而且能避免拉到重複的店家-電機系系會公關長</p>
            <p><a href="#">Learn more about how to sponsor</a></p>
          </div>
        </div>
      </div>
    </div>

app/views/sponsors/_form.html.erb
<h1>申請贊助</h1>
<%= form_for(Task.new) do |f| %>
  
  <div class="field">
    <%= f.label :phone , "聯絡電話"   %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :club , "社團名稱"%><br>
    <%= f.text_field :club %>
  </div>
  <div class="field">
    <%= f.label :club_number, "社團成員數量" %><br>
    <%= f.number_field :club_number %>
  </div>
  <div class="field">
    <%= f.label :university, "大學名稱" %><br>
    <%= f.text_field :university %>
  </div>
<div class="field">
    <%= f.label :mailnumber, "信箱數量" %><br>
    <%= f.number_field :mailnumber %>
  </div>
<div class="field">
    <%= f.label :fanpagelink, "粉絲團或官網連結" %><br>
    <%= f.text_field :fanpagelink %>
  </div>

<div class="field">
    <%= f.label :fanpagenumber, "粉絲團粉絲數量" %><br>
    <%= f.number_field :fanpagenumber %>
  </div>
  <div class="field">
    <%= f.label :finishsponsordate, "何時可以完成贊助" %><br>
    <%= f.text_field :finishsponsordate %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/index.html.erb
<% content_for :js do %>
<%= javascript_include_tag "AnimOnScroll" %>
<%= javascript_include_tag "classie" %>
<%= javascript_include_tag "masonry.pkgd.min" %>
<%= javascript_include_tag "modernizr.custom" %>
<%= javascript_include_tag "imagesloaded" %>
<script>
  new AnimOnScroll( document.getElementById( 'grid' ), {
    minDuration : 0.4,
    maxDuration : 0.7,
    viewportFactor : 0.1
   } );
</script>
<%end%>

<% content_for :css do %>
<%= stylesheet_link_tag "component.css" %>
<%end%>

    <div class="jumbotron">
      <div class="container">
        <h1>贊助列表</h1>
        <p>Sponsor from company&Shop in over 100 companies and 200 shops.</p>
      </div>
    </div>
    <div class="container">
        <div class="row">
        <ul class="grid effect-2" id="grid">

          <%@sponsors.each do |sponsor|%>
            <li >
              <div  class="blk">
                <h2><%= sponsor.name %></h2>
                <%= image_tag( sponsor.img_URL_outer ) %>
                <%= simple_format( sponsor.description ) %>
                <p><%= link_to '贊助內容  >>', sponsor_path(sponsor), class: "btn btn-warning"%></p>
              </div>
            </li>
         <% end%>
       </ul>
    </div>

app/views/sponsors/new.html.erb
<% content_for :js do %>
<%= javascript_include_tag "sponsors" %>
<%end%>
<form id="uploadForm">
    <label>Upload Image File:</label><br/>
    <input name="image" type="file" />
    <input type="submit" value="Submit" />
</form>

app/views/sponsors/show.html.erb
<% content_for :css do %>
<%= stylesheet_link_tag "component.css" %>
<%end%>

<div class="container">
    <div id="column">
        <div class="sponsor_detail">
            <h2><%= @sponsor.name %></h2>
            <%= image_tag( @sponsor.img_URL_inner ) %>
            <br>
            <h2>任務介紹</h2><br>
            <h4><%= simple_format( @sponsor.description) %></h4>
            <br>
            <h2>任務內容</h2><br>
            <h4><%= simple_format( @sponsor.mission ) %></h4>
        </div>
        <div class="sponsor_apply">
            <h2>任務期限</h2>
            <h4><%= simple_format( @sponsor.event_time) %></h4>
            <br>
            <h2>任務對象</h2><br>
            <h4><%= simple_format( @sponsor.participants ) %></h4>
            <br>
            <h2>任務提醒</h2><br>
            <h4><%= simple_format( @sponsor.notice ) %></h4>
            <br>
            <h2>任務獎勵</h2><br>
            <h4><%= simple_format( @sponsor.reward ) %> </h4>
            <br>
            <%= link_to '申請贊助', new_task_path, class: 'btn btn-warning'  %>
        </div>
    </div>
    <div class="feedback">
        <hr>
        <div id="disqus_thread"></div>
    </div>
</div>

<% content_for :js do %>
<%= javascript_include_tag "imagesloaded"%>
    <script type="text/javascript">
        var disqus_shortname = 'isponsor'; // required: replace example with your forum shortname
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<%end%>

app/views/students/show.html.erb
<h1>hello</h1>

app/views/tasks/new.html.erb
<% content_for :js do %>
<%= javascript_include_tag "tasks" %>
<%end%>

<div class="row">
	  <div class="col-md-4"></div>
  <div class="col-md-4"><%= render 'sponsors/form' %>
       <div class="col-md-4"></div>
   </div>